version: "3.11"
services:
  db:
    image: postgres:14
    container_name: db
    restart: always
    command: -p 5430
    expose:
      - 5430
    env_file:
      - .env_docker

  redis:
    image: redis:7
    container_name: redis_app
    command: --port 6371
    expose:
      - 6371

  app:
    build:
      context: .
    env_file:
      - .env_docker
    container_name: django_app
    command: ["/app/docker/app.sh"]
    ports:
      - 8007:8000
    depends_on:
      - db
      - redis
