# Generated by Django 4.1.7 on 2023-06-13 07:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('appsite', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='chat',
            name='status_view',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='order',
            name='file',
            field=models.FileField(null=True, upload_to='file/%Y/%m/%d/', verbose_name='Договор'),
        ),
        migrations.AlterField(
            model_name='chat',
            name='staff',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='staff', to=settings.AUTH_USER_MODEL, verbose_name='Работник'),
        ),
        migrations.AlterField(
            model_name='order',
            name='name',
            field=models.CharField(max_length=50, verbose_name='Название заказа'),
        ),
    ]
