# Generated by Django 4.1.7 on 2023-05-08 07:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appsite', '0002_alter_user_phone_number'),
    ]

    operations = [
        migrations.RenameField(
            model_name='chat',
            old_name='client_id',
            new_name='client',
        ),
        migrations.RenameField(
            model_name='chat',
            old_name='staff_id',
            new_name='staff',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='client_id',
            new_name='client',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='project_id',
            new_name='project',
        ),
    ]
