# Generated by Django 4.1.7 on 2023-05-08 08:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('appsite', '0003_rename_client_id_chat_client_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chat',
            name='staff',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='staff', to=settings.AUTH_USER_MODEL, verbose_name='Работник'),
        ),
    ]
